name: 'Astute-ci-Build-image-run-tests'
on:
  push:
    branches:
      - '**'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: 'Build and push docker image'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true
      - run: |
          git tag
